### PR TITLE
feat(deps): bump npm from 6.14.11 to 7

### PR DESCRIPTION
**Pull request by ybiquitous**
**BREAKING CHANGE: The audit report format has been changed since v7.**

See <https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/>.

- https://github.com/npm/cli/releases/tag/v7.8.0
- https://github.com/npm/cli/compare/v6.14.11...v7.8.0

~~Note: Dependabot does not support npm 7 yet. So package-lock.json is still v1.~~
=> Supported! 🎉

### CODE REVIEW

**Comment by ybiquitous** [comment]
The smoke test failure seems due to:

> The output of `npm audit` has significantly changed both in the human-readable and `--json` output styles.

-- https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/

**Comment by JakeChampion** [comment]
Nice work @ybiquitous 🙌

**Comment by ybiquitous** [comment]
@JakeChampion v3 published! 🎉 
https://github.com/ybiquitous/npm-audit-fix-action/releases/tag/v3.0.0

**Comment by JakeChampion** [comment]
Nice! 👍 I'll upgrade to it tomorrow 😄

**Pull request merged**
